version: "3.8"

services:
  app:
    image: metaculusdiscord:latest
    build:
      context: .
    environment:
      - DOTNET__AppSettings__DiscordToken=random-value-by-test
      - DOTNET__AppSettings__ConnectionStrings__Default=Server=db;Port=5432;Database=metaculus_discord_bot;User Id=metaculus_discord_user;Password=metaculus_discord_password;
    volumes:
      - ./appsettings_template.json:/app/appsettings.json
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      DB_NAME: metaculus_discord_bot
      DB_USER: metaculus_discord_user
      DB_PASSWORD: metaculus_discord_password
      POSTGRES_PASSWORD: rootdbpassword
    expose:
      - 5432
    ports:
      - 5431:5432
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

